<?php
namespace Extension;

use Compiler\JadeCompiler;
use TokenParser\UnsetTokenParser;
use Twig_Environment;
use Twig_ExpressionParser;

class AppExtension extends \Twig_Extension implements \Twig_Extension_GlobalsInterface
{
    public function getName()
    {
        return 'app';
    }

    public function getTokenParsers()
    {
        return array(
            new UnsetTokenParser()
        );
    }

    public function getNodeVisitors()
    {
        return parent::getNodeVisitors(); // TODO: Change the autogenerated stub
    }

    public function getFilters()
    {
        return array(
            new \Twig_SimpleFilter(
                'jade2html',
                function(Twig_Environment $environment, array $context, $jadeSource) {
                    $jadeCompiler = new JadeCompiler($environment);

                    return $jadeCompiler->compile($jadeSource, $context);
                },
                array(
                    'is_safe' => array('html'),
                    'needs_context' => true,
                    'needs_environment' => true,
                )
            ),
            new \Twig_SimpleFilter(
                'print_boolean',
                function($boolean) {
                    return ($boolean) ? 'yes' : 'no';
                }
            ),
            new \Twig_SimpleFilter(
                'print_null',
                function($value) {
                    return (null === $value) ? 'null' : $value;
                }
            )
        );
    }

    public function getTests()
    {
        return array(
            new \Twig_SimpleTest(
                'yellow',
                function($value) {
                    return in_array($value, array('minion'));
                }
            )
        );
    }

    public function getFunctions()
    {
        return array(
            new \Twig_SimpleFunction(
                'env_charset',
                function(Twig_Environment $environment) {
                    return $environment->getCharset();
                },
                array(
                    'needs_environment' => true
                )
            ),
            new \Twig_SimpleFunction(
                'context_var_names',
                function(array $context) {
                    return implode(', ', array_keys($context));
                },
                array(
                    'needs_context' => true
                )
            ),
            new \Twig_SimpleFunction(
                'first_argument',
                function(array $arguments = array())
                {
                    return (isset($arguments[0])) ? $arguments[0] : null;
                },
                array(
                    'is_variadic' => true
                )
            ),
            new \Twig_SimpleFunction(
                'home_*',
                function($color) {
                    return 'the home is '.$color;
                }
            ),
            new \Twig_SimpleFunction('obsolete', function () {
            }, array('deprecated' => true, 'alternative' => 'not_obsolete'))
        );
    }

    public function getOperators()
    {
        return array();
    }

    public function getGlobals()
    {
        return array(
            'blue' => 'bleu'
        );
    }
}